services:
  #traefik:
  #  image: traefik:v2.3
  #  command:
  #    - '--api.insecure=true'
  #    - '--providers.docker=true'
  #    - '--providers.docker.exposedbydefault=false'
  #    - '--entrypoints.web.address=:80'
  #    - '--entrypoints.websecure.address=:443'
  #    - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
  #    - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
  #    - '--entrypoints.web.http.redirections.entrypoint.permanent=true'
  #    - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
  #    - '--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}'
  #    - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
  #  ports:
  #    - '80:80'
  #    - '443:443'
  #    - '8080:8080'
  #  volumes:
  #    - ./data/letsencrypt:/letsencrypt:z
  #    - /var/run/docker.sock:/var/run/docker.sock:ro,z

  #fuseki:
  #  image: semapps/jena-fuseki-webacl
  #  volumes:
  #    - ./data/fuseki:/fuseki:z
  #  ports:
  #    - '3030:3030'
  #  expose:
  #    - '3030'
  #  environment:
  #    ADMIN_PASSWORD: ${FUSEKI_PASSWORD}

  memory-frontend:
    env_file:
      - path: ./frontend/.env
        required: true
    build:
      context: .
      dockerfile: ./docker/frontend.dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_PORT: 4000
    restart: always
    ports:
      - '4000:4000'
    expose:
      - '4000'

  memory-api:
    env_file:
      - path: ./api/.env
        required: true
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
    expose:
      - ${API_PORT}
    ports:
      - '${API_PORT}:${API_PORT}'

  #redis:
  #  image: redis
  #  expose:
  #    - '6379'
  #  volumes:
  #    - ./data/redis:/data:z
  #  command: ['redis-server', '--appendonly', 'yes']

  #arena:
  #  image: activitypods/arena
  #  restart: always
  #  volumes:
  #    - ./docker/arena-prod.json:/opt/arena/src/server/config/index.json:z
  #  depends_on:
  #    - redis
  #  expose:
  #    - '4567'
  #  labels:
  #    - 'traefik.enable=true'
  #    - 'traefik.http.routers.arena.rule=(Host(`${DOMAIN_NAME}`) && Path(`/jobs`))'
  #    - 'traefik.http.routers.arena.entrypoints=websecure'
  #    - 'traefik.http.routers.arena.tls.certresolver=myresolver'
  #  environment:
  #    REDIS_HOST: 'redis'
