name: checks

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - master

jobs:
  linting:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run eslint and prettier on the frontend and api
      - run: bun install && bun lint && bun format --check
        working-directory: ./frontend
      - run: bun install && bunx eslint .
        working-directory: ./api
  testing:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run tests on the api
      - run: bun install && bun test
        working-directory: ./api
